jobs:
  platform_uploads:
    secrets: inherit
    uses: ./.github/workflows/generic.platform_uploads.yml
    with:
      dbo_project_id: 30765
      dbo_project_relations: "[\n  {\"slug\": \"multiverse-inventories\", \"type\"\
        : \"optionalDependency\"},\n  {\"slug\": \"multiverse-portals\", \"type\"\
        : \"optionalDependency\"},\n  {\"slug\": \"multiverse-netherportals\", \"\
        type\": \"optionalDependency\"},\n  {\"slug\": \"multiverse-signportals\"\
        , \"type\": \"optionalDependency\"},\n  {\"slug\": \"vault\", \"type\": \"\
        optionalDependency\"}\n]\n"
      hangar_plugin_dependencies: "{ \"PAPER\": [\n  {\n    \"name\": \"Multiverse-Inventories\"\
        ,\n    \"required\": false,\n    \"platforms\": [\"PAPER\"]\n  },\n  {\n \
        \   \"name\": \"Multiverse-Portals\",\n    \"required\": false,\n    \"platforms\"\
        : [\"PAPER\"]\n  },\n  {\n    \"name\": \"Multiverse-NetherPortals\",\n  \
        \  \"required\": false,\n    \"platforms\": [\"PAPER\"]\n  },\n  {\n    \"\
        name\": \"Multiverse-SignPortals\",\n    \"required\": false,\n    \"platforms\"\
        : [\"PAPER\"]\n  }\n]}\n"
      hangar_slug: Multiverse-Core
      modrinth_dependencies: "[\n  {\"project_id\": \"qvdtDX3s\", \"dependency_type\"\
        : \"optional\"},\n  {\"project_id\": \"8VMk6P0I\", \"dependency_type\": \"\
        optional\"},\n  {\"project_id\": \"vtawPsTo\", \"dependency_type\": \"optional\"\
        },\n  {\"project_id\": \"WuErDeI1\", \"dependency_type\": \"optional\"}\n\
        ]\n"
      modrinth_project_id: 3wmN97b8
      plugin_name: multiverse-core
      target_tag: ${{ inputs.target_tag }}
      upload_dbo: ${{ inputs.upload_dbo }}
      upload_hangar: ${{ inputs.upload_hangar }}
      upload_modrinth: ${{ inputs.upload_modrinth }}
name: 'Call: Platform Uploads'
on:
  repository_dispatch:
    types: trigger-ga___call.platform_uploads.yml
