jobs:
  github_release:
    secrets: inherit
    uses: ./.github/workflows/generic.github_release.yml
    with:
      plugin_name: multiverse-core
      promote_from: ${{ inputs.promote_from }}
      release_mode: ${{ inputs.release_mode }}
      version_bump: ${{ inputs.version_bump }}
name: 'Call: GitHub Release'
on:
  repository_dispatch:
    types: trigger-ga___call.github_release.yml
