jobs:
  dispatch_platform_uploads:
    secrets: inherit
    uses: ./.github/workflows/call.platform_uploads.yml
    with:
      target_tag: ${{ github.event.inputs.target_tag }}
      upload_dbo: ${{ github.event.inputs.upload_dbo }}
      upload_hangar: ${{ github.event.inputs.upload_hangar }}
      upload_modrinth: ${{ github.event.inputs.upload_modrinth }}
name: 'Dispatch: Platform Uploads'
on:
  repository_dispatch:
    types: trigger-ga___dispatch.platform_uploads.yml
