jobs:
  check_version:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Verify input version is prerelease
      run: "if [[ \"${{ github.event.inputs.target_tag }}\" != *\"pre\"* ]]; then\n\
        \    echo \"Version must be a prerelease\"\n    exit 1\nfi\n"
  github_release:
    needs: check_version
    secrets: inherit
    uses: ./.github/workflows/call.github_release.yml
    with:
      promote_from: ${{ github.event.inputs.target_tag }}
      release_mode: promote
  platform_uploads:
    if: needs.github_release.outputs.release_created == 'true'
    needs: github_release
    secrets: inherit
    uses: ./.github/workflows/call.platform_uploads.yml
    with:
      target_tag: ${{ needs.github_release.outputs.tag_name }}
      upload_dbo: 'true'
      upload_hangar: 'true'
      upload_modrinth: 'true'
name: 'Dispatch: Promote Release'
on:
  repository_dispatch:
    types: trigger-ga___dispatch.promote_release.yml
