jobs:
  platform_uploads:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: release-info
      name: Get release info
      uses: cardinalby/git-get-release-action@1.2.4
      with:
        tag: ${{ inputs.target_tag }}
    - continue-on-error: true
      id: release-artifact
      name: Download release artifact
      uses: dsaltares/fetch-gh-release-asset@1.1.1
      with:
        file: ${{ inputs.plugin_name }}-${{ steps.release-info.outputs.tag_name }}.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        version: tags/${{ steps.release-info.outputs.tag_name }}
    - continue-on-error: true
      id: parse-release-type
      name: Parse release type
      run: "if [[ \"${{ steps.release-info.outputs.prerelease }}\" == \"true\" ]];\
        \ then\n    echo Setting release_type to Beta\n    echo \"release_type=Beta\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo Setting release_type to Release\n    echo\
        \ \"release_type=Release\" >> $GITHUB_OUTPUT\nfi\n"
    - continue-on-error: true
      if: ${{ !cancelled() && inputs.upload_modrinth == 'true' }}
      name: Upload to Modrinth
      uses: benwoo1110/modrinth-upload-action@v1
      with:
        api_token: ${{ secrets.MODRINTH_TOKEN }}
        changelog: ${{ steps.release-artifact.outputs.body }}
        dependencies: ${{ inputs.modrinth_dependencies }}
        files: '["${{ github.workspace }}/${{ inputs.plugin_name }}-${{ steps.release-info.outputs.tag_name
          }}.jar"]'
        game_versions: 1.20.1, 1.20, 1.19.4, 1.19.3, 1.19.2, 1.19.1, 1.19, 1.18.2,
          1.18.1, 1.18, 1.17.1, 1.17, 1.16.5, 1.16.4, 1.16.3, 1.16.2, 1.16.1, 1.16,
          1.15.2, 1.15.1, 1.15, 1.14.4, 1.14.3, 1.14.2, 1.14.1, 1.14, 1.13.2, 1.13.1,
          1.13
        loaders: bukkit, spigot, paper
        name: ${{ steps.release-info.outputs.tag_name }}
        project_id: ${{ inputs.modrinth_project_id }}
        version_number: ${{ steps.release-info.outputs.tag_name }}
        version_type: ${{ steps.parse-release-type.outputs.release_type }}
    - continue-on-error: true
      if: ${{ !cancelled() && inputs.upload_dbo == 'true' }}
      name: Upload to DBO
      uses: benwoo1110/dbo-upload-action@v1
      with:
        api_token: ${{ secrets.DBO_UPLOAD_API_TOKEN }}
        changelog: ${{ steps.release-artifact.outputs.body }}
        changelog_type: markdown
        display_name: ${{ steps.release-info.outputs.tag_name }}
        file_path: ${{ github.workspace }}/${{ inputs.plugin_name }}-${{ steps.release-info.outputs.tag_name
          }}.jar
        game_versions: 1.20.1, 1.20, 1.19.4, 1.19.3, 1.19.2, 1.19.1, 1.19, 1.18.2,
          1.18.1, 1.18, 1.17, 1.16, 1.15, 1.14, 1.13
        project_id: ${{ inputs.dbo_project_id }}
        project_relations: ${{ inputs.dbo_project_relations }}
        release_type: ${{ steps.parse-release-type.outputs.release_type }}
    - continue-on-error: true
      if: ${{ !cancelled() && inputs.upload_hangar == 'true' }}
      name: Upload to Hangar
      uses: benwoo1110/hangar-upload-action@v1
      with:
        api_token: ${{ secrets.HANGAR_UPLOAD_TOKEN }}
        channel: ${{ steps.parse-release-type.outputs.release_type }}
        description: ${{ steps.release-artifact.outputs.body }}
        files: '[{"path": "${{ github.workspace }}/${{ inputs.plugin_name }}-${{ steps.release-info.outputs.tag_name
          }}.jar", "platforms": ["PAPER"]}]'
        platform_dependencies: '{"PAPER": ["1.13-1.20.1"]}'
        plugin_dependencies: ${{ inputs.hangar_plugin_dependencies }}
        slug: ${{ inputs.hangar_slug }}
        version: ${{ steps.release-info.outputs.tag_name }}
name: 'Generic: Platform Uploads'
on:
  repository_dispatch:
    types: trigger-ga___generic.platform_uploads.yml
