jobs:
  github_release:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Echo inputs
      run: 'echo "release_mode: ${{ inputs.release_mode }}"

        echo "version_bump: ${{ inputs.version_bump }}"

        echo "promote_from: ${{ inputs.promote_from }}"

        '
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.promote_from }}
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build and test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build -x assemble -x shadowJar
    - continue-on-error: true
      id: release
      name: Create release
      uses: benwoo1110/semantic-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        promote_from: ${{ inputs.promote_from }}
        release_mode: ${{ inputs.release_mode }}
        version_bump: ${{ inputs.version_bump }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_VERSION: ${{ steps.release.outputs.publish_version }}
      if: steps.release.outputs.release_created == 'true'
      name: Publish package
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish -x test
    - continue-on-error: true
      if: steps.release.outputs.release_created == 'true'
      name: Upload release artifact
      uses: svenstaro/upload-release-action@v2
      with:
        asset_name: ${{ inputs.plugin_name }}-${{ steps.release.outputs.tag_name }}.jar
        file: build/libs/${{ inputs.plugin_name }}-${{ steps.release.outputs.publish_version
          }}.jar
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag_name }}
name: 'Generic: GitHub Release'
on:
  repository_dispatch:
    types: trigger-ga___generic.github_release.yml
