jobs:
  test:
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_VERSION: pr${{ github.event.pull_request.number }}
      name: Run unit tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - continue-on-error: true
      name: Artifact output
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.plugin_name }}-pr${{ github.event.pull_request.number }}
        path: build/libs/${{ inputs.plugin_name }}-pr${{ github.event.pull_request.number
          }}.jar
name: 'Generic: Test'
on:
  repository_dispatch:
    types: trigger-ga___generic.test.yml
