jobs:
  checkstyle:
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: dbelyaev/action-checkstyle@v0.8.4
      with:
        checkstyle_config: ./config/mv_checks.xml
        checkstyle_version: 10.12.2
        github_token: ${{ secrets.GITHUB_TOKEN }}
name: 'Generic: Checkstyle'
on:
  repository_dispatch:
    types: trigger-ga___generic.checkstyle.yml
