jobs:
  github_release_on_push:
    secrets: inherit
    uses: ./.github/workflows/call.github_release.yml
    with:
      release_mode: prerelease
      version_bump: prlabel
  platform_uploads_on_push:
    if: needs.github_release_on_push.outputs.release_created == 'true'
    needs: github_release_on_push
    secrets: inherit
    uses: ./.github/workflows/call.platform_uploads.yml
    with:
      target_tag: ${{ needs.github_release_on_push.outputs.tag_name }}
      upload_dbo: 'false'
      upload_hangar: 'false'
      upload_modrinth: 'true'
name: 'Main: Prerelease'
on:
  repository_dispatch:
    types: trigger-ga___main.prerelease.yml
