jobs:
  require_label:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: mheap/github-action-required-labels@v2
      with:
        count: 1
        labels: release:major, release:minor, release:patch, no release
        mode: exactly
name: 'PR: Require Label'
on:
  repository_dispatch:
    types: trigger-ga___pr.require_label.yml
